### ISSUE TITLE
About the usage of GPU memory?

### ISSUE THREAD

**Issue by mmxbc1223** [wangqiang9/Finetune-SVD#4]
I ran the code on a single A6000 (46G) and got an issue of GPU out of memory.
This is my terminal command: accelerate launch train.py.
I use the fully sharded data parallel.
I would like to know your GPU memory and how to run the code.

**Comment by wangqiang9** [comment]
Hi, I use one 80GB A100 to run.

**Comment by DefinitlyEvil** [comment]
Wow it eats a lot of memory then, any chance would it be able to run on my tiny RTX4090? xD 
Muy gracias.

**Comment by hpoghos** [comment]
Hi @wangqiang9, thaks for the grate implementation, 
I'm running the code on a A100, but still get out of memory errors.

**Comment by HaozhouPang** [comment]
> Hi @wangqiang9, thaks for the great implementation, I'm running the code on a A100 80GB, but still get out of memory errors.

Hi @hpoghos , did you make it run on 80GB A100? I also encountered OOM error on a single A100.

**Comment by HaozhouPang** [comment]
The original size 1024*576 seems to cause OOM even with batch size 1 on a 80GB A100, try to change it to a smaller value, 512 works for me with 72GB gpu consumption.

**Comment by DefinitlyEvil** [comment]
Can you do LoRA with it? Thanks.

**Comment by wangqiang9** [comment]
> Can you do LoRA with it? Thanks.

@DefinitlyEvil  Hi, the Lora training code and model comming soon.
